spring:
  # 不是本地部署的Redis或者修改端口的记得修改Redis配置
  data:
    redis:
      port: 6379
      host: 127.0.0.1
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/zoot
    username: root
    password: admin

maa-copilot:
  backup:
    dir: /home/dove/copilotBak
    uri: git@github.com:dragove/zoot-copilot-store.git
    disabled: true
    username: dragove
    email: dragove@qq.com
  info:
    title: ZOOT Plus Backend API
    description: ZOOT Plus Backend API
    version: v2.0.0
    domain: https://prts.maa.plus
    frontend-domain: https://prts.plus
  jwt:
    header: Authorization
    # 默认的JwtToken过期时间，以秒为单位
    expire: 21600
    # JwtToken的加密密钥
    secret: $I_Am_The_Bone_Of_My_Sword!Steel_Is_My_Body_And_Fire_Is_My_Blood!$
  github:
    # GitHub api token
    token: github_pat_xxx
  vcode:
    #默认的验证码失效时间,以秒为单位
    expire: 600
  cache:
    default-expire: 60
  task-cron:
    ark-level: "-"
    copilot-update: "-"
  mail:
    # 邮件通知
    notification: true
  mails:
    # 邮件服务器的SMTP地址
    - host: smtp.163.com
      # 邮件服务器的SMTP的端口 (qq为465,网易为25)
      port: 25
      # 发件人（必须正确，否则发送失败）
      from: user@163.com
      # 用户名(foxmail和qq为发件人邮箱前缀，阿里云邮箱和网易的user是邮箱的完整地址)
      user: user@163.com
      # 密码(拿到的授权码)
      pass: wysqm
      starttls: true
      ssl: false
    - host: smtp.qq.com
      # 使用 ssl 的情况，使用STARTTLS时应该为587（未测试）
      port: 465
      from: user@qq.com
      user: user
      # QQ邮箱的授权码
      pass: qqsqm
      ssl: true
      starttls: false
  copilot:
    min-value-show-not-enough-rating: 50
  sensitive-word:
    path: "classpath:sensitive-word.txt"


springdoc:
  swagger-ui:
    # 开启Swagger UI界面
    enabled: true
  api-docs:
    # 开启api-docs
    enabled: true
  # 配置需要生成接口文档的扫描包
  packages-to-scan: plus.maa.backend

# 调试设置，禁用邮箱发送，改为本地控制台打印验证码
#debug:
#  email:
#    no-send: true

# 如果需要打印SQL，则启用下面日志
#logging:
#  level:
#    org.ktorm: debug
